config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  get 'home', to: "pages#home", as: 'home'
  root to: "pages#home"
  get "about", to: "pages#about", as: "about"
  get "work", to: "pages#work", as: "work"
  get "contact", to: "pages#contact", as: "contact"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        render :home
    end

    def about
        #render :about
    end

    def work
        #render :work
    end

    def contact
        #render :contact
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DevPortfolio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<header>
<h1>About me</h1>

</header>

<article>
    <br>
    <p>My name is Nicholas Folis. I am currently taking COMP-3081-002 (Software Programming) this semester, and <br>
    this is currently my fourth semester at the University of Memphis. My major is Computer Programming, and I hope <br>
    to one day become experienced in video game programming!</p>

</article>

app/views/pages/contact.html.erb
<h1>Contact Information</h1>

<h3>GitHub</h3>
<p>If you like, you may always find me on GitHub by the name <%= link_to "Spongehubman", "https://github.com/Spongehubman"%>.</p>

app/views/pages/home.html.erb
<header>
<h1>My Portfolio Website</h1>

<p>Welcome to my portfolio website!</p>

<nav>
    <ul>
        <!-- In Rails, you instead use this method instead of <a>. -->
        <!-- Use link_to {text you wish to represent the link}, with pagename_path 
        referring to the path object to pagename.-->
        <li><%= link_to 'Home', home_path %></li>
        <li><%= link_to 'About', about_path %></li>
        <li><%= link_to 'My Work', work_path %></li>
        <li><%= link_to 'Contact', contact_path %></li>
    </ul>
</nav>
</header>

app/views/pages/work.html.erb
<header>
    <h1>Some of My Works this Semester.</h1>
</header>

<p>Here is a list of selected works I have worked on during this semester:</p>

<h3 id="work1"><%= link_to "sa8-act2: Ruby classes", "https://github.com/Spongehubman/sa8-act2" %></h3>
<p>Each of the files in this repository focuses on an aspect of Ruby classes and methods. I really liked <br>
learning how to use them.</p><br>


<h3 id="work2"><%= link_to "TDD-Based Poker Game (Midterm Project)", "https://github.com/Spongehubman/midterm-project" %></h3>
<p>This project took advantage of using the TDD development method to creating a poker game. <br>
This I really liked working on this poker gamem, and it was fun to play as well. Unfortunately, <br>
this game only properly works with "full house" and "four-of-a-kind" hands, but the prinicple is the same.</p><br>

<h3 id="work3"><%= link_to "sa11-act2: Practice Using Regular Expressions (in Ruby)", "https://github.com/Spongehubman/sa11-act2" %></h3>
<p>This was the first of two assignments involving the use of Regular Expressions (Regex), and it <br>
really helped me in getting used to using regular expression commands in Ruby files.</p><br>

<h3 id="work4"><%= link_to "sa15-act1: Quiz Webpage Using HTML, CSS, and JavaScript", "https://github.com/Spongehubman/sa15-act1"%></h3>
<p>This project uses HTML, CSS, and JavaScript to create a quiz webpage based on material from this course. <br>
I really liked making this project, as it helped me to remember (if not learn) how to use radio button sets in <br>
which only one can be selected; it also helped me to get used to insertting text in HTML documents using JavaScript.<br>
How many questions can <i>you</i> answer correctly?</p><br>


<script>

document.getElementById("work1")

</script>